### ISSUE TITLE
 Legs don't look normal in the floor reflection

### ISSUE THREAD

**Issue by adem4ik** [jekyllgrim/Alice-Toys-of-Madness#3]
1. Add [Relighting](https://www.moddb.com/mods/relighting) mod
2. Start Doom 2's MAP02
3. Look into the river

Result: It seems like thighs are missing.
 ![изображение](https://github.com/user-attachments/assets/927891cc-0e3e-4287-9568-fcc82d8d05eb)
Video: https://github.com/user-attachments/assets/9b8f813c-4757-4d7d-8367-7ec9880491ab

**Comment by jekyllgrim** [comment]
That's what the actual Alice's model from American McGee's Alice looks like. Thighs are obscured (presumably intentionally) by a part of the skirt mesh textured as undergarment. Not a bug.
