### ISSUE TITLE
[Suggestion] Increase height-change threshold for jump/skip animation

### ISSUE THREAD

**Issue by dileepvr** [jekyllgrim/Alice-Toys-of-Madness#5]
Running around relatively flat spaces in, say, Lullaby, in third person triggers her jump/skip animation too frequently. You barely see her just walking/running.

**Comment by jekyllgrim** [comment]
I made it time-based, but other than that, implemented in 10919ddefb36038e6dd1da8bcc2d53cd0e608aa1
